name: Keep Render Warm
on:
  schedule:
    - cron: "*/14 * * * *"   # כל 14 דקות
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Wake Render
        run: curl -s https://telegram-bot-edugo-1.onrender.com
